# -*- mode: ruby -*-
# vi: set ft=ruby :

$master_script = <<MASTER_SCRIPT
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)
echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
add-apt-repository -y ppa:webupd8team/java
sudo apt-get -y update
sudo apt-get install -y oracle-java8-installer
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo apt-get install -y marathon mesosphere
MASTER_SCRIPT

$client_script = <<CLIENT_SCRIPT
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)
echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-get -y update
sudo apt-get install -y mesos
CLIENT_SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.define "mesos-master-1" do |m1|
    m1.vm.network "private_network", ip: "192.0.2.1"
    m1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1000]
      v.customize ["modifyvm", :id, "--name", "m1"]
    end
    m1.vm.provision "shell", inline: $master_script
  end
  config.vm.define "mesos-master-2" do |m2|
    m2.vm.network "private_network", ip: "192.0.2.2"
    m2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1000]
      v.customize ["modifyvm", :id, "--name", "m2"]
    end
    m2.vm.provision "shell", inline: $master_script
  end
  config.vm.define "mesos-master-3" do |m3|
    m3.vm.network "private_network", ip: "192.0.2.3"
    m3.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1000]
      v.customize ["modifyvm", :id, "--name", "m3"]
    end
    m3.vm.provision "shell", inline: $master_script
  end
  config.vm.define "mesos-slave-1" do |s1|
    s1.vm.network "private_network", ip: "192.0.2.51"
    s1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "s1"]
    end
    s1.vm.provision "shell", inline: $client_script
  end
  config.vm.define "mesos-slave-2" do |s2|
    s2.vm.network "private_network", ip: "192.0.2.52"
    s2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "s2"]
    end
    s2.vm.provision "shell", inline: $client_script
  end
  config.vm.define "mesos-slave-3" do |s3|
    s3.vm.network "private_network", ip: "192.0.2.53"
    s3.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "s3"]
    end
    s3.vm.provision "shell", inline: $client_script
  end
end
