# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 4096]
  end

  config.vm.provision :shell, inline: <<-SHELL
    cat > /tmp/test.yml <<EOF
---
- hosts: localhost
  vars:
    jenkins_hostname: localhost
  roles:
  - geerlingguy.jenkins
EOF
    apt-add-repository ppa:ansible/ansible
    apt-get update
    apt-get install -y ansible git
    ansible-galaxy install geerlingguy.jenkins
    ansible-playbook /tmp/test.yml
  SHELL

#  config.vm.provision :ansible do |ansible|
#    ansible.playbook = "gerrit.yml"
#    ansible.sudo = true
    # debug is on
#    ansible.verbose = "vvvv"
#  end
end
